title: David Salami Data Analytics Portfolio
logo: David.jpg
description: A data analyst with good experience working across different sectors, highly skilled in Excel, SQL and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
